// Blanks and ignored characters

blank : ( WS | newline )

newline : ( WS* COMMENT? NEWLINE )+

WS_ALL: WS
WS: /[ \t\f\v]+/
NEWLINE: (/\r?\n/)+
COMMENT: /;[^\n]*/

// Numbers

DIGIT: "0".."9"
INT: DIGIT+
DECIMAL: (INT "." [INT] | "." INT)
SIGNED_INT: ["+" | "-"] INT

EXP: ("E" | "e") SIGNED_INT
FLOAT: (INT EXP | DECIMAL [EXP])
SIGNED_FLOAT: ["+" | "-"] FLOAT

NUMBER: (FLOAT | INT)
SIGNED_NUMBER: ["+" | "-"] NUMBER
NUMERIC: (NUMBER | SIGNED_NUMBER)

// Fixed values for $THETA and $OMEGA

fix : blank* FIX blank*
FIX : "FIXED" | "FIXE" | "FIX"
