root : _empty_lines _options? _end?

_options: (_options _sep)? option

_empty_lines: _sep?

_sep: ws
    | ws newline
    | ws COMMENT newline
    | newline
    | COMMENT newline

_end: COMMENT
    | ws COMMENT?
    | ws newline COMMENT?
    | ws COMMENT newline COMMENT?
    | newline COMMENT?
    | COMMENT newline COMMENT?

newline: (newline COMMENT?)? NEWLINE WS?
ws: WS

option: KEY ("=" VALUE)?

KEY: ATOM
VALUE: ATOM
ATOM: /\([^)]*\)|[^\s=;]+/

%import .definitions (COMMENT, WS, NEWLINE)
