#!/usr/bin/python3

import json
import urllib.request
import re
from pathlib import Path

# Starting point for script generated by Gemini

# Target Python tag (e.g., cp315, py315, or general py3)
TARGET_PYTHON = "3.15"
TARGET_TAGS = (f"cp{TARGET_PYTHON.replace('.', '')}", "py3", "py2.py3")


def check_pypi_wheel(package_name: str) -> bool:
    url = f"https://pypi.org/pypi/{package_name}/json"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Pharmpy/check-wheels'})
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode())

        # Get releases files for the latest release
        latest_version = data['info']['version']
        urls = data['releases'].get(latest_version, [])

        for file_info in urls:
            filename = file_info['filename']
            # Check for wheel files and python version tags
            if filename.endswith('.whl'):
                # Pure Python wheels (py3-none-any) or 3.15 CPython wheels (cp315-...)
                python_tag = file_info.get('python_version', '')
                if any(tag in filename or tag in python_tag for tag in TARGET_TAGS):
                    return True
        return False
    except Exception as e:
        print(f"Error checking {package_name}: {e}")
        return False


def parse_requirements(file_path: str = "requirements.txt"):
    skip = ("csscompressor", "tornado")
    packages = []
    path = Path(file_path)
    if not path.exists():
        print(f"File {file_path} not found.")
        return packages

    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith('#'):
            # Extract package name (stripping version specifiers)
            pkg_name = re.split(r'[<>=!~;]', line)[0].strip()
            if pkg_name and pkg_name not in skip:
                packages.append(pkg_name)
    return packages


if __name__ == "__main__":
    deps = parse_requirements("../requirements.txt")
    print(f"Checking {len(deps)} dependencies for Python {TARGET_PYTHON} wheel support...\n")

    missing = []
    for pkg in deps:
        has_wheel = check_pypi_wheel(pkg)
        status = "✅ Wheel available" if has_wheel else "❌ No Python 3.15 wheel"
        print(f"{pkg:<25} {status}")
        if not has_wheel:
            missing.append(pkg)

    print("\n--- Summary ---")
    if missing:
        print(f"The following {len(missing)} packages need Python {TARGET_PYTHON} wheels:")
        for m in missing:
            print(f"  - {m}")
    else:
        print(f"All dependencies have Python {TARGET_PYTHON} compatible wheels!")
